# Generated by Django 2.1.7 on 2019-03-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('created', 'owner')},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='code',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='language',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='style',
        ),
    ]
